debug: true
control_rate: 20.0 
torque_on_startup: true
torque_off_on_shutdown: true
dynamixels:
  port_info:
    port_name: /dev/ttyUSB0
    protocol_version: 2
    baud_rate: 3000000
  read_values: # write values are given by the control mode
    read_position: true
    read_velocity: true
    read_torque: false
  control_mode: position
  device_info: # read/write all devices with one packet
    arm_joint:
      id: 0
  write_registers:
    arm_yaw_joint:
      max_position_limit: 3.14 # radian
    lidar_spin_joint:
      goal_velocity: 1 # radian per second
  publish_registers:
    present_temperature: 
      topic: /dynamixels/temperature
      frequency: 10 # Hz
      