joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50 

arm_traj_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_joint
    
arm_controller:
  type: "position_controllers/JointPositionController"
  joint: arm_joint
  
  

